from wtforms import Form, StringField, TextAreaField, validators

class SubmissionForm(Form):
    Open = StringField('Title', [validators.Length(min=0, max=30)])
    High = StringField('Title', [validators.Length(min=0, max=30)])
    Low = StringField('Title', [validators.Length(min=0, max=30)])
    Close = StringField('Title', [validators.Length(min=0, max=30)])
    Volume = StringField('Title', [validators.Length(min=0, max=30)])
    T3_Vol_Diff = StringField('Title', [validators.Length(min=0, max=30)])
    T3_Close_Diff = StringField('Title', [validators.Length(min=0, max=30)])
    T3_Open_Diff = StringField('Title', [validators.Length(min=0, max=30)])
    T2_Vol_Diff = StringField('Title', [validators.Length(min=0, max=30)])
    T2_Close_Diff = StringField('Title', [validators.Length(min=0, max=30)])
    T2_Open_Diff = StringField('Title', [validators.Length(min=0, max=30)])
    T1_Vol_Diff = StringField('Title', [validators.Length(min=0, max=30)])
    T1_Close_Diff = StringField('Title', [validators.Length(min=0, max=30)])
    T1_Open_Diff = StringField('Title', [validators.Length(min=0, max=30)])
    Prior_Day_Vert_Delta_Ratio = StringField('Title', [validators.Length(min=0, max=30)])
    Retracement_Signal = StringField('Title', [validators.Length(min=0, max=30)])
    Prior_Day_Derivative = StringField('Title', [validators.Length(min=0, max=30)])